site_name: Campus Connect
nav:
  - API: api/index.md
  - Assets: assets/index.md
  - Author: author/index.md
  - Contributing: api/index.md
  - Development: development/index.md
  - FAQ: faq/index.md
  - Features: features/index.md
  - Future Changes: futurechanges/index.md
  - Images: images/index.md
  - Installation: installation/index.md
  - License: license/index.md
  - Safety: safety/index.md
  - Search: search/index.md
  - Uninstall: uninstall/index.md
  - Usage: usage/index.md
theme:
  name: readthedocs
  content:
    max_width: none
extra_css:
  - css/style.css
features:
  - navigation.expand
